# Generated by Django 4.0.4 on 2022-05-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='studentFile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
