# Generated by Django 4.0.4 on 2022-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requirement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpost',
            name='theFile',
            field=models.FileField(blank=True, upload_to='teacher-files/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='studentFile',
            field=models.FileField(blank=True, upload_to='student-files/'),
        ),
    ]
