# Generated by Django 4.0.4 on 2022-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requirement', '0002_teacherpost_thefile_alter_work_studentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
