# Generated by Django 4.0.4 on 2022-05-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclassification',
            old_name='is_teacher',
            new_name='isTeacher',
        ),
    ]
